# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7be9a536a2db91a326aa559c558423ac04979c7e9e6e2b6ac38b15c370d6c283d4e0d116335bf93adcd44c965c926446800a71eac71308fede61e901a628763

test:
  secret_key_base: ef0b42fd78837f73501b29cb49e2818d48dfdca47b5b720e396f75597d84cf3a6f51a97d37c5d81dfb4b4f998dca325034863fc9f80cccbaef7937bff9eeecca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
